# Generated by Django 4.1.3 on 2022-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoldNums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favNum", models.FloatField()),
                ("underNum", models.FloatField()),
            ],
        ),
    ]
